# Generated by Django 5.2.17 on 2026-09-09 14:22

import django_geoaddress.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReadonly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name', max_length=255, verbose_name='Name')),
                ('address', django_geoaddress.fields.GeoaddressField(help_text='Cannot be changed once it has been set.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Readonly location',
                'verbose_name_plural': 'Readonly locations',
                'ordering': ['-created_at'],
            },
        ),
    ]
