# Generated by Django 5.2.17 on 2026-09-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_locationreadonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreadonly',
            name='addressbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readonly_locations', to='app.addressbook', verbose_name='Address book'),
        ),
    ]
